"""The "From contents" button: GET /api/boxes/{code}/summary-suggestion.

Proposed, never applied -- the page puts the line in the field and the
autosaver decides the rest. Two things are being pinned here: that what is
nested inside a container counts as its contents, and that a model writing the
line is an *improvement* on the assembled one rather than a dependency. Every
route to "the model did not answer" has to end in the assembled line.

No test reaches a model: a Config built directly has `phrase_summaries` off,
and the ones that want a phraser pass their own.
"""

import pytest
from fastapi.testclient import TestClient

from movingbox import db
from movingbox.api import app as app_module
from movingbox.api.app import create_app


@pytest.fixture
def client(config):
    with TestClient(create_app(config)) as c:
        yield c


@pytest.fixture
def conn(client, config):
    """A second handle on the same database, for what the API will not set."""
    c = db.connect(config.db_path)
    yield c
    c.close()


@pytest.fixture
def empty(client):
    return client.post("/api/boxes", json={}).json()["code"]


def phrased(client, answer):
    """Put a phraser behind the endpoint. `answer` may be an exception."""

    class Says:
        name = "stub"

        def __init__(self):
            self.seen = None

        def phrase(self, contents, *, model):
            self.seen = contents
            if isinstance(answer, Exception):
                raise answer
            return answer

    said = Says()
    client.app.dependency_overrides[app_module.get_phraser] = lambda: said
    return said


def autogenerated(conn, code, summary):
    """Leave a child's summary as the photo worker would: not the person's.

    Written straight to the row because there is no way to ask for it through
    the API, on purpose -- `summary_source` is never client-settable.
    """
    conn.execute(
        "UPDATE boxes SET content_summary = ?, summary_source = 'auto' WHERE code = ?",
        (summary, code),
    )
    conn.commit()


def stock(client, code, *names):
    for name in names:
        client.post(f"/api/boxes/{code}/items", json={"name": name})


class TestTheAssembledSummary:
    def test_a_summary_is_suggested_from_the_items(self, client, empty):
        client.post(f"/api/boxes/{empty}/items", json={"name": "baking pan", "qty": 3})
        client.post(f"/api/boxes/{empty}/items", json={"name": "kettle"})

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["summary"] == "3 baking pans, kettle"

    def test_suggesting_does_not_change_the_box(self, client, empty):
        # Same rule as the photo draft: propose, never apply.
        client.post(f"/api/boxes/{empty}/items", json={"name": "kettle"})

        client.get(f"/api/boxes/{empty}/summary-suggestion")

        assert client.get(f"/api/boxes/{empty}").json()["content_summary"] is None

    def test_what_is_nested_inside_is_suggested_too(self, client, empty):
        # Three bags in a crate: "3 bags", not an empty suggestion and not
        # "bag, bag, bag".
        for _ in range(3):
            client.post("/api/boxes", json={"kind": "bag", "parent_code": empty})

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["summary"] == "3 bags"

    def test_a_nested_record_offers_its_own_summary_to_its_container(self, client, empty):
        client.post(
            "/api/boxes",
            json={"kind": "bag", "parent_code": empty, "content_summary": "winter coats"},
        )

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["summary"] == "winter coats"

    def test_what_is_inside_a_nested_box_reaches_the_container(self, client, empty):
        # Asked for as "if there are subitems, collect text from those". The
        # crate could only say "large box" where the box holds books.
        inner = client.post(
            "/api/boxes", json={"kind": "box", "size": "large", "parent_code": empty}
        ).json()["code"]
        client.post(f"/api/boxes/{inner}/items", json={"name": "hardback novel", "qty": 12})

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["summary"] == "12 hardback novels"

    def test_it_reaches_a_grandchild_too(self, client, empty):
        middle = client.post("/api/boxes", json={"kind": "box", "parent_code": empty}).json()[
            "code"
        ]
        inner = client.post("/api/boxes", json={"kind": "bag", "parent_code": middle}).json()[
            "code"
        ]
        client.post(f"/api/boxes/{inner}/items", json={"name": "wool blanket", "qty": 2})

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["summary"] == "2 wool blankets"

    def test_an_autogenerated_summary_gives_way_to_the_items_behind_it(self, client, conn, empty):
        # Its summary is a rephrasing of those items. Taking both would feed
        # the same contents twice, once sharp and once blurred, and the blur
        # would win a little more at every level.
        inner = client.post("/api/boxes", json={"kind": "box", "parent_code": empty}).json()["code"]
        client.post(f"/api/boxes/{inner}/items", json={"name": "vinyl LP", "qty": 40})
        autogenerated(conn, inner, "Miscellaneous items")

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["summary"] == "40 vinyl LPs"

    def test_a_summary_a_person_typed_on_a_child_is_what_is_used(self, client, empty):
        inner = client.post(
            "/api/boxes",
            json={"kind": "bag", "parent_code": empty, "content_summary": "Grandma's tea set"},
        ).json()["code"]
        client.post(f"/api/boxes/{inner}/items", json={"name": "cup", "qty": 6})

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["summary"] == "Grandma's tea set"

    def test_a_nested_records_items_can_carry_it_past_the_model_threshold(self, client, empty):
        # A container used to contribute one phrase, so a crate holding one
        # box stayed below ENOUGH and was never phrased. Its contents count.
        inner = client.post("/api/boxes", json={"kind": "box", "parent_code": empty}).json()["code"]
        for name in ("stock pot", "stand mixer", "colander"):
            client.post(f"/api/boxes/{inner}/items", json={"name": name})
        said = phrased(client, "Kitchen gear - a stock pot and a stand mixer")

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["source"] == "model"
        assert [thing["name"] for thing in said.seen] == ["stock pot", "stand mixer", "colander"]

    def test_a_box_with_no_items_suggests_nothing(self, client, empty):
        assert client.get(f"/api/boxes/{empty}/summary-suggestion").json()["summary"] == ""

    def test_an_unknown_box_is_404(self, client):
        assert client.get("/api/boxes/B-9999/summary-suggestion").status_code == 404


class TestWhenAModelWritesIt:
    def test_the_model_line_is_used_and_labelled_as_its_own(self, client, empty):
        stock(client, empty, "stock pot", "stand mixer", "baking pan", "colander")
        phrased(client, "Kitchen gear - a stock pot, a stand mixer and baking pans")

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion == {
            "summary": "Kitchen gear - a stock pot, a stand mixer and baking pans",
            "source": "model",
        }

    def test_the_model_is_shown_what_is_nested_inside_as_well(self, client, empty):
        stock(client, empty, "kettle", "toaster")
        for _ in range(3):
            client.post("/api/boxes", json={"kind": "bag", "parent_code": empty})
        said = phrased(client, "Kitchen things and three bags")

        client.get(f"/api/boxes/{empty}/summary-suggestion")

        assert [thing["name"] for thing in said.seen] == ["kettle", "toaster", "bag"]
        assert said.seen[-1]["qty"] == 3

    def test_a_model_that_does_not_answer_costs_nothing_but_the_phrasing(self, client, empty):
        # The whole point: offline, the button still works.
        stock(client, empty, "stock pot", "stand mixer", "baking pan")
        phrased(client, ConnectionError("nothing answered at http://localhost:11434"))

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion == {
            "summary": "stock pot, stand mixer, baking pan",
            "source": "assembled",
        }

    def test_an_empty_box_is_never_sent_to_a_model(self, client, empty):
        said = phrased(client, "Empty - nothing at all")

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion == {"summary": "", "source": "assembled"}
        assert said.seen is None


class TestNoTestReachesAModel:
    def test_the_suite_assembles_rather_than_phrasing(self, client, empty):
        # A Config built directly has phrase_summaries off, so the endpoint
        # gets no phraser at all. If this fails, every press of the button in
        # the suite is a call to Ollama.
        stock(client, empty, "stock pot", "stand mixer", "baking pan", "colander")

        suggestion = client.get(f"/api/boxes/{empty}/summary-suggestion").json()

        assert suggestion["source"] == "assembled"

    def test_there_is_no_phraser_unless_the_config_asks_for_one(self, config):
        assert app_module.build_phraser(config) is None

    def test_the_stub_provider_phrases_without_a_model(self, config):
        # What MOVING_VISION_PROVIDER=stub gives the browser checks.
        stubbed = config.replace(phrase_summaries=True, vision_provider="stub")

        phraser = app_module.build_phraser(stubbed)

        assert phraser.name == "stub"
        assert phraser.phrase([{"name": "kettle", "qty": 1}], model="m").startswith("Assorted")
