"""The photo-analysis API: the contract the PWA is built against.

docs/superpowers/specs/2026-09-18-photo-analysis.md is the contract; these pin
it. The worker thread is off here (a Config built directly never starts it), so
jobs are run by hand with a stub provider -- nothing talks to a model.
"""

import io

import pytest
from fastapi.testclient import TestClient
from PIL import Image

from movingbox import analysis
from movingbox.api.app import create_app
from movingbox.vision import base

ANALYSIS_KEYS = {"status", "remaining_ms", "total_ms", "items_found", "error", "items", "summary"}


def a_jpeg(colour=(120, 90, 60)) -> bytes:
    buffer = io.BytesIO()
    Image.new("RGB", (400, 300), colour).save(buffer, format="JPEG")
    return buffer.getvalue()


class Sees:
    name = "stub"

    def __init__(self, *items):
        self.items = items

    def draft(self, images, *, model):
        return base.BoxDraft(
            summary="things", items=[base.DraftItem(name=n, qty=q) for n, q in self.items]
        )


@pytest.fixture
def client(config):
    with TestClient(create_app(config)) as c:
        yield c


def upload(client, code, colour=(120, 90, 60)):
    response = client.post(
        f"/api/boxes/{code}/photos", files={"file": ("p.jpg", a_jpeg(colour), "image/jpeg")}
    )
    assert response.status_code == 201
    return response.json()


def run_queue(config, *items):
    told = []
    worker = analysis.Analyst(
        config, provider_factory=lambda: Sees(*items), publish=lambda k, c: told.append((k, c))
    )
    while worker.run_once():
        pass
    return told


class TestUploading:
    def test_a_new_photo_is_queued_without_being_asked(self, client):
        code = client.post("/api/boxes", json={}).json()["code"]

        photo = upload(client, code)

        assert set(photo["analysis"]) == ANALYSIS_KEYS
        assert photo["analysis"]["status"] == "pending"
        assert photo["analysis"]["remaining_ms"] > 0

    def test_the_photo_list_carries_each_photos_state(self, client):
        code = client.post("/api/boxes", json={}).json()["code"]
        upload(client, code)

        photos = client.get(f"/api/boxes/{code}/photos").json()

        assert [set(p["analysis"]) for p in photos] == [ANALYSIS_KEYS]

    def test_a_retried_upload_is_not_analysed_twice(self, client, config):
        code = client.post("/api/boxes", json={}).json()["code"]
        upload(client, code)
        upload(client, code)  # same bytes: dedupes to the same photo

        run_queue(config, ("kettle", 1))

        assert [i["name"] for i in client.get(f"/api/boxes/{code}/items").json()] == ["kettle"]

    def test_a_loose_things_photo_is_just_a_photo(self, client):
        code = client.post("/api/boxes", json={"kind": "item"}).json()["code"]

        assert upload(client, code)["analysis"] is None

    def test_the_worker_does_not_run_in_the_test_suite(self, client):
        # A Config built directly has auto_analyse off, so no test ever starts a
        # thread that reaches for a model. If this fails, every upload in the
        # suite is a call to Ollama.
        assert client.app.state.analyst is None


class TestWhatTheWorkerDoesShowsUp:
    def test_found_items_appear_as_autogenerated(self, client, config):
        code = client.post("/api/boxes", json={}).json()["code"]
        upload(client, code)

        run_queue(config, ("kettle", 1), ("mug", 3))

        items = client.get(f"/api/boxes/{code}/items").json()
        assert [(i["name"], i["qty"], i["source"]) for i in items] == [
            ("kettle", 1, "ai"), ("mug", 3, "ai")]

    def test_the_photo_says_what_was_found(self, client, config):
        code = client.post("/api/boxes", json={}).json()["code"]
        upload(client, code)

        run_queue(config, ("kettle", 1), ("mug", 3))

        state = client.get(f"/api/boxes/{code}/photos").json()[0]["analysis"]
        assert (state["status"], state["items_found"], state["remaining_ms"]) == ("done", 2, 0)

    def test_the_autogenerated_summary_appears_on_the_record(self, client, config):
        code = client.post("/api/boxes", json={}).json()["code"]
        upload(client, code)

        run_queue(config, ("kettle", 1), ("mug", 3))

        assert client.get(f"/api/boxes/{code}").json()["content_summary"] == "kettle, 3 mugs"

    def test_a_summary_saved_from_the_app_is_kept(self, client, config):
        code = client.post("/api/boxes", json={}).json()["code"]
        client.patch(f"/api/boxes/{code}", json={"content_summary": "Grandma's tea set"})
        upload(client, code)

        run_queue(config, ("kettle", 1))

        assert client.get(f"/api/boxes/{code}").json()["content_summary"] == "Grandma's tea set"

    def test_a_summary_given_at_creation_is_kept(self, client, config):
        code = client.post("/api/boxes", json={"content_summary": "tea things"}).json()["code"]
        upload(client, code)

        run_queue(config, ("kettle", 1))

        assert client.get(f"/api/boxes/{code}").json()["content_summary"] == "tea things"

    def test_every_device_is_told(self, client, config):
        code = client.post("/api/boxes", json={}).json()["code"]
        upload(client, code)

        told = run_queue(config, ("kettle", 1))

        assert ("photos.changed", code) in told   # started, and finished
        assert ("items.changed", code) in told
        assert ("box.updated", code) in told

    def test_summary_source_is_not_something_a_client_can_set(self, client):
        code = client.post("/api/boxes", json={}).json()["code"]

        response = client.patch(f"/api/boxes/{code}", json={"summary_source": "auto"})

        assert response.status_code == 422


class TestAskingAgain:
    def test_a_photo_can_be_requeued(self, client, config):
        code = client.post("/api/boxes", json={}).json()["code"]
        photo = upload(client, code)
        run_queue(config, ("kettle", 1))

        response = client.post(f"/photos/{photo['id']}/analyse")

        assert response.status_code == 202
        assert response.json()["analysis"]["status"] == "pending"

    def test_an_unknown_photo_is_a_404(self, client):
        assert client.post("/photos/999/analyse").status_code == 404

    def test_a_loose_things_photo_cannot_be_analysed(self, client):
        code = client.post("/api/boxes", json={"kind": "item"}).json()["code"]
        photo = upload(client, code)

        assert client.post(f"/photos/{photo['id']}/analyse").status_code == 409


class TestRenamingAnItem:
    def item(self, client, code, **fields):
        return client.post(f"/api/boxes/{code}/items", json={"name": "mug", **fields}).json()

    def test_an_item_can_be_renamed(self, client):
        code = client.post("/api/boxes", json={}).json()["code"]
        item = self.item(client, code)

        response = client.patch(f"/api/items/{item['id']}", json={"name": "espresso cups"})

        assert response.status_code == 200
        assert response.json()["name"] == "espresso cups"

    def test_renaming_an_autogenerated_item_makes_it_yours(self, client, config):
        code = client.post("/api/boxes", json={}).json()["code"]
        upload(client, code)
        run_queue(config, ("mug", 3))
        item = client.get(f"/api/boxes/{code}/items").json()[0]
        assert item["source"] == "ai"

        renamed = client.patch(f"/api/items/{item['id']}", json={"name": "espresso cups"}).json()

        assert renamed["source"] == "manual"

    def test_the_quantity_can_be_changed_too(self, client):
        code = client.post("/api/boxes", json={}).json()["code"]
        item = self.item(client, code)

        assert client.patch(f"/api/items/{item['id']}", json={"qty": 6}).json()["qty"] == 6

    def test_an_empty_name_is_refused(self, client):
        code = client.post("/api/boxes", json={}).json()["code"]
        item = self.item(client, code)

        assert client.patch(f"/api/items/{item['id']}", json={"name": "   "}).status_code == 422

    def test_an_unknown_item_is_a_404(self, client):
        assert client.patch("/api/items/999", json={"name": "x"}).status_code == 404

    def test_an_unknown_field_is_refused(self, client):
        code = client.post("/api/boxes", json={}).json()["code"]
        item = self.item(client, code)

        response = client.patch(f"/api/items/{item['id']}", json={"source": "manual"})

        assert response.status_code == 422

    def test_the_rename_is_searchable(self, client):
        code = client.post("/api/boxes", json={}).json()["code"]
        item = self.item(client, code)
        client.patch(f"/api/items/{item['id']}", json={"name": "samovar"})

        found = client.get("/api/search", params={"q": "samovar"}).json()

        assert [b["code"] for b in found] == [code]
