"""Building a one-line summary from the itemised contents.

Plain assembly, not a model: the items have already been typed or reviewed, so
a summary of them should be instant, predictable and available offline.
"""

from movingbox import summarise


def items(*names):
    return [{"name": n, "qty": 1} for n in names]


def test_a_short_list_becomes_a_comma_list():
    assert summarise.from_items(items("kettle", "toaster")) == "kettle, toaster"


def test_quantities_are_carried_through():
    contents = [{"name": "baking pan", "qty": 3}, {"name": "kettle", "qty": 1}]

    assert summarise.from_items(contents) == "3 baking pans, kettle"


def test_a_plural_is_not_invented_for_a_word_already_plural():
    contents = [{"name": "scissors", "qty": 2}, {"name": "boxes", "qty": 2}]

    assert summarise.from_items(contents) == "2 scissors, 2 boxes"


def test_duplicates_are_merged_rather_than_repeated():
    contents = [{"name": "mug", "qty": 2}, {"name": "Mug", "qty": 3}]

    assert summarise.from_items(contents) == "5 mugs"


def test_an_empty_list_gives_an_empty_summary():
    assert summarise.from_items([]) == ""


def test_the_summary_is_capped_to_fit_a_label():
    contents = items(*[f"thing number {n}" for n in range(200)])

    result = summarise.from_items(contents)

    assert len(result) <= summarise.MAX_LENGTH


def test_truncation_says_how_many_were_left_out():
    # "and 12 more" is far more useful on tape than a sentence cut mid-word.
    contents = items(*[f"item {n}" for n in range(60)])

    result = summarise.from_items(contents)

    assert "more" in result
    assert not result.endswith(",")


def test_items_keep_their_given_order():
    # The order things were listed usually reflects what is most notable.
    assert summarise.from_items(items("piano", "sock")).startswith("piano")


def node(
    depth=1,
    kind="bag",
    *,
    box_id=None,
    parent_id=None,
    summary=None,
    source="manual",
    size=None,
    items=(),
):
    """One record of a subtree, shaped as store.subtree returns it."""
    return {
        "id": box_id,
        "code": f"B-{box_id or 0:04d}",
        "parent_id": parent_id,
        "depth": depth,
        "kind": kind,
        "size": size,
        "content_summary": summary,
        "summary_source": source,
        "items": [{"name": n, "qty": q} for n, q in items],
    }


def named(contents):
    return [(thing["name"], thing["qty"]) for thing in contents]


class TestWhatOneNestedRecordContributes:
    """The rule is: the most concrete text that record has.

    Never a summary *and* the items it was made from: that is the same contents
    twice, once sharp and once blurred, and the blur compounds at every level.
    """

    def test_a_summary_a_person_typed_wins_over_its_items(self):
        # Their words about their own things beat any list we could build.
        inside = node(summary="Grandma's tea set", source="manual", items=[("cup", 6)])

        assert summarise.node_contents(inside) == [{"name": "Grandma's tea set", "qty": 1}]

    def test_items_win_over_an_autogenerated_summary(self):
        # The summary is a rephrasing of those very items, often by this
        # module. Taking it instead would throw away the specifics.
        inside = node(summary="Assorted items", source="auto", items=[("kettle", 1), ("mug", 3)])

        assert named(summarise.node_contents(inside)) == [("kettle", 1), ("mug", 3)]

    def test_an_autogenerated_summary_is_used_when_there_are_no_items(self):
        # A photo described but not itemised: the sentence is all there is.
        inside = node(summary="A cabinet of labelled drawers", source="auto")

        assert summarise.node_contents(inside) == [
            {"name": "A cabinet of labelled drawers", "qty": 1}
        ]

    def test_with_neither_it_contributes_what_it_is(self):
        assert summarise.node_contents(node(1, "crate", size="large")) == [
            {"name": "large crate", "qty": 1}
        ]

    def test_a_loose_thing_inside_is_named_by_what_it_is(self):
        assert summarise.node_contents(node(kind="item")) == [{"name": "loose item", "qty": 1}]


class TestGatheringAWholeSubtree:
    def test_the_records_own_items_come_first(self):
        nodes = [node(0, "crate", items=[("kettle", 1)]), node(1, items=[("scarf", 2)])]

        assert named(summarise.contents(nodes)) == [("kettle", 1), ("scarf", 2)]

    def test_the_records_own_summary_is_not_fed_back_to_itself(self):
        # It is the line we are about to write; it would describe itself.
        nodes = [node(0, "crate", summary="Kitchen things", items=[("kettle", 1)])]

        assert named(summarise.contents(nodes)) == [("kettle", 1)]

    def test_a_childs_items_reach_the_container(self):
        nodes = [node(0, "crate"), node(1, "box", size="large", items=[("book", 4), ("album", 2)])]

        assert named(summarise.contents(nodes)) == [("book", 4), ("album", 2)]

    def test_a_grandchilds_items_reach_it_too(self):
        nodes = [
            node(0, "crate", box_id=1),
            node(1, "box", box_id=2, parent_id=1),
            node(2, "bag", box_id=3, parent_id=2, items=[("glove", 2)]),
        ]

        assert named(summarise.contents(nodes)) == [("glove", 2)]

    def test_a_container_that_holds_something_does_not_also_say_it_is_a_box(self):
        # What is inside speaks for it, rather than "large box".
        nodes = [
            node(0, "crate", box_id=1),
            node(1, "box", box_id=2, parent_id=1, size="large"),
            node(2, "bag", box_id=3, parent_id=2, items=[("book", 4)]),
        ]

        assert named(summarise.contents(nodes)) == [("book", 4)]

    def test_but_an_empty_container_still_says_what_it_is(self):
        # Otherwise a crate of three empty bags summarises to nothing at all.
        nodes = [
            node(0, "crate", box_id=1),
            node(1, "box", box_id=2, parent_id=1, size="large"),
        ]

        assert named(summarise.contents(nodes)) == [("large box", 1)]

    def test_three_empty_bags_still_read_as_three_bags(self):
        # One counted phrase, not three lines.
        nodes = [node(0, "crate"), node(1), node(1), node(1)]

        assert summarise.from_subtree(nodes) == "3 bags"

    def test_closeness_decides_the_order(self):
        nodes = [
            node(0, "crate", items=[("kettle", 1)]),
            node(1, items=[("scarf", 1)]),
            node(2, items=[("glove", 1)]),
        ]

        assert [thing["name"] for thing in summarise.contents(nodes)] == [
            "kettle",
            "scarf",
            "glove",
        ]

    def test_the_same_thing_in_two_places_is_counted_once(self):
        nodes = [
            node(0, "crate", items=[("mug", 2)]),
            node(1, items=[("Mug", 3)]),
        ]

        assert named(summarise.contents(nodes)) == [("mug", 5)]

    def test_the_material_is_capped_and_the_furthest_away_goes_first(self):
        # A crate of five boxes of twenty is a hundred names for one printed
        # line. What is nearest is what the line should be spent on.
        near = node(0, "crate", items=[(f"near {n}", 1) for n in range(30)])
        far = node(2, items=[(f"far {n}", 1) for n in range(30)])

        gathered = [thing["name"] for thing in summarise.contents([near, far])]

        assert len(gathered) == summarise.MAX_THINGS
        assert gathered[0] == "near 0"
        assert "far 29" not in gathered

    def test_nothing_nested_is_just_the_records_items(self):
        nodes = [node(0, "box", items=[("kettle", 1), ("toaster", 1)])]

        assert summarise.from_subtree(nodes) == "kettle, toaster"

    def test_an_empty_subtree_summarises_to_nothing(self):
        assert summarise.from_subtree([]) == ""
        assert summarise.from_subtree([node(0, "box")]) == ""


class TestTheNormalisedName:
    """One rule for "the same thing", shared with what a photo's reading merges.

    It lives here because both callers already import this module and only one
    of them may import the other.
    """

    def test_case_and_spacing_do_not_make_two_things(self):
        assert summarise.name_key("Stock  Pot") == summarise.name_key("stock pot")

    def test_nor_does_a_trailing_plural(self):
        assert summarise.name_key("resistors") == summarise.name_key("resistor")
        assert summarise.name_key("boxes") == summarise.name_key("box")

    def test_a_short_word_keeps_its_ending(self):
        # "gas" is not two "ga"s.
        assert summarise.name_key("gas") != summarise.name_key("ga")


class TestTheItemsOfAWholeSubtree:
    """What the view's expanded contents list is built from.

    Asked for as "include items from subitems with a small item-id heading,
    putting them after box-level items. sort and deduplicate items when showing
    them."
    """

    def test_each_record_keeps_its_own_items(self):
        groups = summarise.grouped_items(
            [
                node(0, "box", box_id=1, items=(("resistors", 3),)),
                node(1, "tub", box_id=2, parent_id=1, items=(("a soldering iron", 1),)),
            ]
        )

        assert [g["code"] for g in groups] == ["B-0001", "B-0002"]
        assert [i["name"] for i in groups[0]["items"]] == ["resistors"]
        assert [i["name"] for i in groups[1]["items"]] == ["a soldering iron"]

    def test_the_order_is_the_subtree_s_own_closeness(self):
        groups = summarise.grouped_items(
            [
                node(0, "crate", box_id=1, items=(("tape", 1),)),
                node(1, "tub", box_id=2, parent_id=1, items=(("wire", 1),)),
                node(2, "bag", box_id=3, parent_id=2, items=(("clips", 1),)),
            ]
        )

        assert [g["code"] for g in groups] == ["B-0001", "B-0002", "B-0003"]

    def test_repeats_within_a_record_become_one_line_with_the_count_summed(self):
        groups = summarise.grouped_items(
            [
                node(0, "box", box_id=1, items=(("resistors", 3), ("Resistor", 1), ("LEDs", 2))),
            ]
        )

        assert groups[0]["items"] == [
            {"name": "LEDs", "qty": 2},
            {"name": "resistors", "qty": 4},
        ]

    def test_the_same_name_in_two_records_stays_two_lines(self):
        # The crate's tape and the tub's tape are two rolls in two places, and
        # that is exactly what the headings exist to say.
        groups = summarise.grouped_items(
            [
                node(0, "crate", box_id=1, items=(("tape", 1),)),
                node(1, "tub", box_id=2, parent_id=1, items=(("tape", 1),)),
            ]
        )

        assert [g["items"] for g in groups] == [
            [{"name": "tape", "qty": 1}],
            [{"name": "tape", "qty": 1}],
        ]

    def test_items_are_sorted_within_a_record_whatever_order_they_were_added(self):
        groups = summarise.grouped_items(
            [
                node(0, "box", box_id=1, items=(("wire", 1), ("Anvil", 1), ("clips", 1))),
            ]
        )

        assert [i["name"] for i in groups[0]["items"]] == ["Anvil", "clips", "wire"]

    def test_a_record_that_lists_nothing_is_not_a_group(self):
        groups = summarise.grouped_items(
            [
                node(0, "crate", box_id=1, items=()),
                node(1, "tub", box_id=2, parent_id=1, items=(("wire", 1),)),
            ]
        )

        assert [g["code"] for g in groups] == ["B-0002"]

    def test_nothing_anywhere_is_no_groups(self):
        assert summarise.grouped_items([]) == []
        assert summarise.grouped_items(None) == []

    def test_a_summary_is_not_an_item(self):
        # node_contents falls back to a record's summary, or to what it is;
        # this is a list of *items*, so a record with none contributes none.
        groups = summarise.grouped_items(
            [
                node(0, "box", box_id=1, items=(("wire", 1),)),
                node(1, "bag", box_id=2, parent_id=1, summary="winter coats", items=()),
            ]
        )

        assert [g["code"] for g in groups] == ["B-0001"]
