"""Photo analysis in the background: queue, worker, merge and estimates.

Uploading a photo queues a job; one worker thread runs them oldest-first (the
model is the bottleneck) and applies what the model saw, protecting a person's
own work:

- items the model adds are tagged ``source='ai'``;
- an item a person typed is never renamed, re-counted or removed;
- a summary a person typed is never overwritten -- only an empty one, or one
  that was itself autogenerated (``boxes.summary_source = 'auto'``).

Jobs live in ``ai_jobs``, so a restart loses nothing -- see `recover`.
"""

from __future__ import annotations

import dataclasses
import json
import logging
import sqlite3
import statistics
import threading
import time
from collections.abc import Callable
from typing import Any

from . import db, kinds, search, spend, store, summarise
from .config import Config
from .vision import base

log = logging.getLogger(__name__)

#: A job's assumed length before there is history: between a warm run and a cold one.
DEFAULT_ESTIMATE_MS = 20_000

#: How many finished jobs the estimate looks back over.
HISTORY = 10

#: Event kinds, spelled here so this module does not import the API layer.
PHOTOS_CHANGED = "photos.changed"
ITEMS_CHANGED = "items.changed"
BOX_UPDATED = "box.updated"


# --- the queue ----------------------------------------------------------------


def enqueue(
    conn: sqlite3.Connection,
    config: Config,
    photo_id: int,
    *,
    again: bool = False,
    detail: bool = False,
) -> int | None:
    """Queue one photo for analysis. Returns the job id, or None if not queued.

    Idempotent unless `again=True`. `detail=True` is the closer look, whose
    findings are merged like any other read: it adds, never replaces.
    """
    photo = conn.execute(
        """
        SELECT photos.id, photos.box_id, boxes.kind
          FROM photos JOIN boxes ON boxes.id = photos.box_id
         WHERE photos.id = ?
        """,
        (photo_id,),
    ).fetchone()
    if photo is None:
        return None
    # A single thing has no contents to list.
    if not kinds.holds_contents(photo["kind"] or kinds.DEFAULT):
        return None

    existing = conn.execute(
        "SELECT id, status FROM ai_jobs WHERE photo_id = ? ORDER BY id DESC LIMIT 1", (photo_id,)
    ).fetchone()
    if existing is not None and (not again or existing["status"] in ("pending", "running")):
        return existing["id"]
    # A re-run adds a row: the old ones are the history estimates are made of,
    # and a photo's state is its latest job.
    cursor = conn.execute(
        """
        INSERT INTO ai_jobs (box_id, photo_id, provider, model, prompt_version, status, detail)
        VALUES (?, ?, ?, ?, ?, 'pending', ?)
        """,
        (
            photo["box_id"],
            photo_id,
            config.vision_provider,
            # The model tried first; the worker writes back the one that answered.
            config.vision_model_for(detail=detail),
            base.PROMPT_VERSION,
            int(detail),
        ),
    )
    return cursor.lastrowid


def recover(conn: sqlite3.Connection) -> int:
    """Put back jobs the last process died holding. Returns how many."""
    cursor = conn.execute("""
        UPDATE ai_jobs SET status = 'pending', started_at = NULL
         WHERE status = 'running' AND photo_id IS NOT NULL
        """)
    return cursor.rowcount


# --- estimates ------------------------------------------------------------------


def estimate_ms(conn: sqlite3.Connection, model: str) -> int:
    """How long one photo is expected to take on this model.

    The median, so one cold start does not make every later photo look slow.
    """
    rows = conn.execute(
        """
        SELECT duration_ms FROM ai_jobs
         WHERE status = 'done' AND photo_id IS NOT NULL
           AND model = ? AND duration_ms IS NOT NULL
         ORDER BY id DESC LIMIT ?
        """,
        (model, HISTORY),
    ).fetchall()
    if not rows:
        return DEFAULT_ESTIMATE_MS
    return int(statistics.median(row["duration_ms"] for row in rows))


def _elapsed_ms(conn: sqlite3.Connection, since: str | None) -> int:
    if not since:
        return 0
    row = conn.execute(
        "SELECT CAST((julianday('now') - julianday(?)) * 86400000 AS INTEGER) AS ms", (since,)
    ).fetchone()
    return max(0, row["ms"] or 0)


def state_of(conn: sqlite3.Connection, photo_id: int) -> dict[str, Any] | None:
    """A photo's analysis, in the shape the API promises. None if never queued.

    ``remaining_ms`` is the best guess at time left *from now*; ``total_ms`` is
    the whole expected span of the job, so a countdown ring's fraction complete
    is ``1 - remaining_ms / total_ms``.
    """
    job = conn.execute(
        "SELECT * FROM ai_jobs WHERE photo_id = ? ORDER BY id DESC LIMIT 1", (photo_id,)
    ).fetchone()
    if job is None:
        return None

    state: dict[str, Any] = {
        "status": job["status"],
        "remaining_ms": 0,
        "total_ms": 0,
        "items_found": None,
        # The closer look rather than the quick read.
        "detail": bool(job["detail"]),
        # Once done, the model that actually answered.
        "provider": job["provider"],
        "model": job["model"],
        # What was seen in *this* photo, not the record's merged list.
        "items": None,
        "summary": None,
        "error": job["error"],
    }

    if job["status"] == "done":
        try:
            seen = json.loads(job["raw_response"] or "{}")
        except ValueError:
            seen = {}
        state["items"] = [
            {"name": item.get("name", ""), "qty": item.get("qty") or 1}
            for item in seen.get("items", [])
            if isinstance(item, dict) and item.get("name")
        ]
        state["items_found"] = len(state["items"])
        state["summary"] = seen.get("summary") or None
        state["total_ms"] = job["duration_ms"] or 0
        return state
    if job["status"] == "error":
        return state

    each = estimate_ms(conn, job["model"])
    # Everything queued ahead finishes first; a running job has used some of its share.
    ahead = conn.execute(
        """
        SELECT COUNT(*) AS n,
               MAX(CASE WHEN status = 'running' THEN started_at END) AS running_since
          FROM ai_jobs
         WHERE photo_id IS NOT NULL AND status IN ('pending', 'running') AND id < ?
        """,
        (job["id"],),
    ).fetchone()
    spent = _elapsed_ms(
        conn, job["started_at"] if job["status"] == "running" else ahead["running_since"]
    )
    span = each * (ahead["n"] + 1)

    state["remaining_ms"] = max(0, span - spent)
    # From when the job was queued, so a countdown keeps its place across a reload.
    state["total_ms"] = max(
        state["remaining_ms"], _elapsed_ms(conn, job["created_at"]) + state["remaining_ms"]
    )
    return state


# --- applying what was seen -------------------------------------------------------


#: What makes two item names the same thing. It moved to `summarise` when the
#: view's expanded contents list needed the same rule: one normaliser, and
#: this module already imports that one.
_key = summarise.name_key


def merge_items(conn: sqlite3.Connection, code: str, found: list[base.DraftItem]) -> bool:
    """Add what is new; raise autogenerated counts; leave a person's items be.

    Returns whether anything changed.
    """
    existing = {_key(item["name"]): item for item in store.list_items(conn, code)}
    changed = False

    for item in found:
        name = " ".join(item.name.split())
        if not name:
            continue
        match = existing.get(_key(name))
        if match is None:
            added = store.add_item(
                conn, code, name=name, qty=item.qty, category=item.category, source="ai"
            )
            existing[_key(name)] = added
            changed = True
        elif match["source"] == "ai" and item.qty > (match["qty"] or 1):
            # Only ever upwards: a worse angle does not un-see things.
            store.update_item(conn, match["id"], qty=item.qty, keep_source=True)
            match["qty"] = item.qty
            changed = True
    return changed


def refresh_summary(conn: sqlite3.Connection, code: str, *, described: str | None = None) -> bool:
    """Rebuild the summary from the contents -- if it is the model's to rebuild.

    `described`, the model's own sentence about the photo, is used only when
    there are no contents to build from.

    Plain assembly, never a model: this runs behind a vision call that is
    already the bottleneck. Only "From contents" phrases (see `phrasing.py`).
    """
    box = store.get_box(conn, code)
    if box is None:
        return False
    mine = box["summary_source"] == "auto" or not (box["content_summary"] or "").strip()
    if not mine:
        return False

    fallback = " ".join((described or "").split())[: base.SUMMARY_MAX].strip()
    # What is nested inside counts as contents, as it does for "From contents".
    summary = summarise.from_subtree(store.subtree(conn, code)) or fallback or None
    if summary == box["content_summary"] and box["summary_source"] == "auto":
        return False
    conn.execute(
        """
        UPDATE boxes SET content_summary = ?, summary_source = 'auto',
                         updated_at = datetime('now')
         WHERE id = ?
        """,
        (summary, box["id"]),
    )
    search.reindex_box(conn, box["id"])
    return True


# --- the worker ---------------------------------------------------------------------


class Analyst(threading.Thread):
    """Runs queued photo analyses, one at a time, until stopped.

    `run_once` is all of the logic, and what tests drive; the thread only
    decides when to call it.
    """

    def __init__(
        self,
        config: Config,
        *,
        provider_factory: Callable[[], base.VisionProvider],
        publish: Callable[[str, str], Any],
        idle: float = 5.0,
    ):
        super().__init__(name="photo-analyst", daemon=True)
        self.config = config
        self._provider_factory = provider_factory
        self._publish = publish
        self._idle = idle
        self._wake = threading.Event()
        self._stopping = threading.Event()

    def wake(self) -> None:
        """A photo was just queued: do not wait out the idle timer."""
        self._wake.set()

    def stop(self) -> None:
        self._stopping.set()
        self._wake.set()

    def run(self) -> None:
        conn = db.connect(self.config.db_path)
        try:
            recovered = recover(conn)
            if recovered:
                log.info("requeued %d photo analyses interrupted by a restart", recovered)
        finally:
            conn.close()

        while not self._stopping.is_set():
            try:
                worked = self.run_once()
            except Exception:  # noqa: BLE001 - the worker must outlive any one job
                log.exception("photo analysis worker hit an unexpected error")
                worked = False
            if not worked:
                self._wake.wait(self._idle)
                self._wake.clear()

    def run_once(self) -> bool:
        """Claim and run the oldest pending job. False if there was none."""
        conn = db.connect(self.config.db_path)
        try:
            job = self._claim(conn)
            if job is None:
                return False
            self._run(conn, job)
            return True
        finally:
            conn.close()

    def _claim(self, conn: sqlite3.Connection) -> dict[str, Any] | None:
        # One statement, so a restart overlapping a shutdown cannot claim a job twice.
        row = conn.execute("""
            UPDATE ai_jobs SET status = 'running', started_at = datetime('now')
             WHERE id = (SELECT id FROM ai_jobs
                          WHERE status = 'pending' AND photo_id IS NOT NULL
                          ORDER BY id LIMIT 1)
            RETURNING *
            """).fetchone()
        return dict(row) if row else None

    def _run(self, conn: sqlite3.Connection, job: dict[str, Any]) -> None:
        target = conn.execute(
            """
            SELECT photos.filename, boxes.code, boxes.deleted_at
              FROM photos JOIN boxes ON boxes.id = photos.box_id
             WHERE photos.id = ?
            """,
            (job["photo_id"],),
        ).fetchone()
        path = self.config.photo_dir / target["filename"] if target else None
        if target is None or target["deleted_at"] or not path.is_file():
            # The photo or its record went while the job was queued.
            conn.execute("DELETE FROM ai_jobs WHERE id = ?", (job["id"],))
            return

        code = target["code"]
        self._publish(PHOTOS_CHANGED, code)  # pending -> running

        provider = self._provider_factory()
        # Per job, since a queue can cross the cap halfway down.
        if hasattr(provider, "local_only") and spend.over_cap(conn, self.config):
            log.info("photo analysis is over its budget; reading locally")
            provider = provider.local_only()

        started = time.monotonic()
        try:
            draft = provider.draft([path.read_bytes()], model=job["model"])
        except Exception as failure:  # noqa: BLE001 - every provider fails differently
            conn.execute(
                """
                UPDATE ai_jobs SET status = 'error', error = ?, duration_ms = ?,
                                   completed_at = datetime('now')
                 WHERE id = ?
                """,
                (str(failure) or type(failure).__name__, _since(started), job["id"]),
            )
            # A call that reached a model and then failed was still billed.
            spend.record(conn, job["id"], getattr(provider, "last", None))
            self._publish(PHOTOS_CHANGED, code)
            return

        conn.execute(
            """
            UPDATE ai_jobs SET status = 'done', raw_response = ?, duration_ms = ?,
                               completed_at = datetime('now')
             WHERE id = ?
            """,
            (json.dumps(dataclasses.asdict(draft)), _since(started), job["id"]),
        )
        # Who answered, and what it cost.
        spend.record(conn, job["id"], getattr(provider, "last", None))

        # The record may have been deleted while the model was thinking.
        if store.get_box(conn, code) is not None:
            items_changed = merge_items(conn, code, draft.items)
            summary_changed = refresh_summary(conn, code, described=draft.summary)
            if items_changed:
                self._publish(ITEMS_CHANGED, code)
            if summary_changed or items_changed:
                self._publish(BOX_UPDATED, code)
        self._publish(PHOTOS_CHANGED, code)


def _since(started: float) -> int:
    return int((time.monotonic() - started) * 1000)
