"""Turn an itemised list into the one line that goes on the label.

Plain assembly, no model: instant, deterministic and offline.
"""

from __future__ import annotations

from typing import Any

from . import kinds

#: Characters; the same cap as a model's summary (vision.base.SUMMARY_MAX).
MAX_LENGTH = 240

#: Words already plural or unchanged in the plural.
UNCOUNTED = {
    "scissors",
    "trousers",
    "glasses",
    "clothes",
    "linens",
    "tongs",
    "pliers",
    "shears",
}


def plural(name: str, qty: int) -> str:
    if qty <= 1:
        return name
    lowered = name.lower()
    if lowered in UNCOUNTED or lowered.endswith(("s", "x", "ch", "sh")):
        return name
    return f"{name}s"


def _merge(contents: list[dict[str, Any]]) -> list[tuple[str, int]]:
    """Combine repeats of the same thing, keeping first-seen order."""
    order: list[str] = []
    totals: dict[str, int] = {}
    labels: dict[str, str] = {}

    for item in contents:
        name = str(item.get("name") or "").strip()
        if not name:
            continue
        key = name.lower()
        if key not in totals:
            order.append(key)
            labels[key] = name
            totals[key] = 0
        try:
            totals[key] += max(1, int(item.get("qty") or 1))
        except (TypeError, ValueError):
            totals[key] += 1

    return [(labels[key], totals[key]) for key in order]


def from_items(contents: list[dict[str, Any]], max_length: int = MAX_LENGTH) -> str:
    """A label-ready summary of ``contents``; too long, it ends "..., and N more"."""
    merged = _merge(contents or [])
    if not merged:
        return ""

    parts = [f"{qty} {plural(name, qty)}" if qty > 1 else name for name, qty in merged]

    summary = ", ".join(parts)
    if len(summary) <= max_length:
        return summary

    kept: list[str] = []
    for index, part in enumerate(parts):
        # Reserve room for the "and N more" that will follow if we stop here.
        still_to_come = len(parts) - index - 1
        candidate = ", ".join([*kept, part])
        if len(candidate) + len(f", and {still_to_come} more") > max_length:
            break
        kept.append(part)

    if not kept:  # a single item longer than the whole budget
        return parts[0][: max_length - 1].rstrip(" ,") + "…"

    left = len(parts) - len(kept)
    return ", ".join(kept) + (f", and {left} more" if left else "")


def describe(child: dict[str, Any]) -> str:
    """What one nested record contributes: its summary, else what it is ("large box").

    The size is spelled in full, unlike the list's "XL".
    """
    summary = str(child.get("content_summary") or "").strip()
    if summary:
        return summary
    kind = kinds.label_for(str(child.get("kind") or kinds.DEFAULT)).lower()
    size = str(child.get("size") or "").strip()
    return f"{size} {kind}" if size else kind


#: How many distinct things a summary is built from, nearest first, however
#: deep the tree goes.
MAX_THINGS = 40


def node_contents(node: dict[str, Any], *, holds: bool = False) -> list[dict[str, Any]]:
    """What one nested record contributes: the most concrete text it has.

    In order: a summary a person typed; its items; an autogenerated summary;
    what it is ("large box") -- unless it `holds` something, which then speaks
    for it.

    Items go ahead of an autogenerated summary because that summary usually
    rephrases those same items; taking it would blur the line further at each
    level of nesting.
    """
    summary = str(node.get("content_summary") or "").strip()
    items = node.get("items") or []

    if summary and node.get("summary_source") != "auto":
        return [{"name": summary, "qty": 1}]
    if items:
        return [dict(item) for item in items]
    if summary:
        return [{"name": summary, "qty": 1}]
    return [] if holds else [{"name": describe(node), "qty": 1}]


def contents(nodes: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Everything a record holds, from `store.subtree`'s nodes, merged and nearest first.

    The record's own summary is not read: it is the line about to be written,
    and would otherwise describe itself more vaguely with every press. Repeats
    merge across levels, so three empty bags read as "3 bags".
    """
    # Records with something inside them, which speaks for them instead.
    holding = {n.get("parent_id") for n in nodes or () if n.get("parent_id") is not None}

    gathered: list[dict[str, Any]] = []
    for node in nodes or ():
        if node.get("depth", 0) == 0:
            gathered.extend(dict(item) for item in node.get("items") or [])
        else:
            gathered.extend(node_contents(node, holds=node.get("id") in holding))

    return [{"name": name, "qty": qty} for name, qty in _merge(gathered)[:MAX_THINGS]]


def from_subtree(nodes: list[dict[str, Any]], max_length: int = MAX_LENGTH) -> str:
    """A label-ready summary of a record and everything nested inside it."""
    return from_items(contents(nodes), max_length)
