"""Turn an itemised list into the one line that goes on the label.

Deliberately not a model. The items have already been typed, or reviewed after
a photo draft, so summarising them is a formatting job: it should be instant,
give the same answer every time, and work with no network.
"""

from __future__ import annotations

from typing import Any

from . import kinds

#: Matches the label renderer's cap, so the summary never arrives pre-broken.
MAX_LENGTH = 240

#: Words that are already plural, or unchanged in the plural. Short on purpose:
#: a wrong plural on tape is mildly embarrassing, a missing one is invisible.
UNCOUNTED = {
    "scissors",
    "trousers",
    "glasses",
    "clothes",
    "linens",
    "tongs",
    "pliers",
    "shears",
}


def plural(name: str, qty: int) -> str:
    if qty <= 1:
        return name
    lowered = name.lower()
    if lowered in UNCOUNTED or lowered.endswith(("s", "x", "ch", "sh")):
        return name
    return f"{name}s"


def _merge(contents: list[dict[str, Any]]) -> list[tuple[str, int]]:
    """Combine repeats of the same thing, keeping first-seen order."""
    order: list[str] = []
    totals: dict[str, int] = {}
    labels: dict[str, str] = {}

    for item in contents:
        name = str(item.get("name") or "").strip()
        if not name:
            continue
        key = name.lower()
        if key not in totals:
            order.append(key)
            labels[key] = name
            totals[key] = 0
        try:
            totals[key] += max(1, int(item.get("qty") or 1))
        except (TypeError, ValueError):
            totals[key] += 1

    return [(labels[key], totals[key]) for key in order]


def from_items(contents: list[dict[str, Any]], max_length: int = MAX_LENGTH) -> str:
    """A label-ready summary of ``contents``.

    Over-long lists are cut at a whole item and finished with "and N more",
    which tells you something useful; a sentence severed mid-word does not.
    """
    merged = _merge(contents or [])
    if not merged:
        return ""

    parts = [f"{qty} {plural(name, qty)}" if qty > 1 else name for name, qty in merged]

    summary = ", ".join(parts)
    if len(summary) <= max_length:
        return summary

    kept: list[str] = []
    for index, part in enumerate(parts):
        # Reserve room for the "and N more" that will follow if we stop here.
        still_to_come = len(parts) - index - 1
        candidate = ", ".join([*kept, part])
        if len(candidate) + len(f", and {still_to_come} more") > max_length:
            break
        kept.append(part)

    if not kept:  # a single item longer than the whole budget
        return parts[0][: max_length - 1].rstrip(" ,") + "…"

    left = len(parts) - len(kept)
    return ", ".join(kept) + (f", and {left} more" if left else "")


def describe(child: dict[str, Any]) -> str:
    """What one nested record contributes to its container's summary.

    Its own summary when it has one -- a bag that says "winter coats" is far
    more use on the outer label than the word "bag". Otherwise what it *is*,
    in the words the list rows use: "large box", "bag", "loose item".

    The size is spelled in full here where the list abbreviates "extra large"
    to "XL": that abbreviation exists for a narrow cell that cannot wrap, and
    a summary is a sentence.
    """
    summary = str(child.get("content_summary") or "").strip()
    if summary:
        return summary
    kind = kinds.label_for(str(child.get("kind") or kinds.DEFAULT)).lower()
    size = str(child.get("size") or "").strip()
    return f"{size} {kind}" if size else kind


#: How many distinct things a summary is built from, however deep the tree
#: goes. A crate of five boxes of twenty is a hundred names for one printed
#: line: past this the material is only diluting what is nearest. The same
#: number `vision.base.ITEMS_MAX` uses, for the same judgement -- more than
#: forty distinct things in one container is a container of "misc".
MAX_THINGS = 40


def node_contents(node: dict[str, Any], *, holds: bool = False) -> list[dict[str, Any]]:
    """What one nested record contributes: the most concrete text it has.

    In order:

    1. **a summary a person typed** -- their own words about their own things
       beat any list assembled for them;
    2. **otherwise its items**, which are the ground truth of what is in there;
    3. **otherwise an autogenerated summary** -- all there is when a photo was
       described but never itemised;
    4. **otherwise what it is**: "large box", "bag", "loose item" -- unless it
       `holds` something, in which case nothing: whatever is inside it is
       about to speak for it, and "large box" beside the books in that box is
       the very noise this exists to remove.

    Items ahead of an autogenerated summary is the clause that keeps vagueness
    from compounding. Such a summary is a rephrasing of those very items, very
    often by this module, so taking both would feed the same contents twice --
    once specific, once blurred -- and the blur wins a little more at each
    level until a crate three deep is described as "Miscellaneous items".
    Taking the items instead means the blurring only ever happens once, at the
    top, where the line is actually being written.
    """
    summary = str(node.get("content_summary") or "").strip()
    items = node.get("items") or []

    if summary and node.get("summary_source") != "auto":
        return [{"name": summary, "qty": 1}]
    if items:
        return [dict(item) for item in items]
    if summary:
        return [{"name": summary, "qty": 1}]
    return [] if holds else [{"name": describe(node), "qty": 1}]


def contents(nodes: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Everything a record holds, gathered from its whole subtree.

    `nodes` is what `store.subtree` returns: the record at depth 0, then its
    children, then theirs. Asked for as "if there are subitems, collect text
    from those for summarization, not just the local items" -- a crate holding
    a box of twenty things should be able to say what those things are.

    The record's **own summary is deliberately not read**: it is the line about
    to be written, and feeding it back in would have it describing itself,
    more vaguely every time the button was pressed.

    Merging is what makes three empty bags read as "3 bags" rather than three
    lines, and it is why the whole subtree is flattened into one list rather
    than nested: `_merge` counts repeats wherever they turn up, so two mugs in
    the crate and three in a bag inside it are five mugs.

    Order is closeness, because that is the order a summary should spend its
    room in, and the cap therefore drops what is furthest away.
    """
    # Which of these records have something of their own inside them. An empty
    # bag is worth naming ("3 bags"); a box with books in it is not, because
    # the books are in this list too.
    holding = {n.get("parent_id") for n in nodes or () if n.get("parent_id") is not None}

    gathered: list[dict[str, Any]] = []
    for node in nodes or ():
        if node.get("depth", 0) == 0:
            gathered.extend(dict(item) for item in node.get("items") or [])
        else:
            gathered.extend(node_contents(node, holds=node.get("id") in holding))

    return [{"name": name, "qty": qty} for name, qty in _merge(gathered)[:MAX_THINGS]]


def from_subtree(nodes: list[dict[str, Any]], max_length: int = MAX_LENGTH) -> str:
    """A label-ready summary of a record and everything nested inside it."""
    return from_items(contents(nodes), max_length)
